// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );




class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-D_TAYMzm9PBuQwsIgHBvvO56NARZL0',
    appId: '1:386411267159:web:2a7a5c34de936ee4b48f12',
    messagingSenderId: '386411267159',
    projectId: 'teeth-management-system-b60a7',
    authDomain: 'teeth-management-system-b60a7.firebaseapp.com',
    storageBucket: 'teeth-management-system-b60a7.firebasestorage.app',
    measurementId: 'G-ETMMT9PYJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP2KjIw6EG-bxVVrTkjnhpfOOtw5EFYdg',
    appId: '1:386411267159:android:a422e190d261d911b48f12',
    messagingSenderId: '386411267159',
    projectId: 'teeth-management-system-b60a7',
    storageBucket: 'teeth-management-system-b60a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW87naCPBdunkJGcT0mELkY78ZiToAQ0Y',
    appId: '1:386411267159:ios:1eb429c7134e65e3b48f12',
    messagingSenderId: '386411267159',
    projectId: 'teeth-management-system-b60a7',
    storageBucket: 'teeth-management-system-b60a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterMoblieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW87naCPBdunkJGcT0mELkY78ZiToAQ0Y',
    appId: '1:386411267159:ios:1eb429c7134e65e3b48f12',
    messagingSenderId: '386411267159',
    projectId: 'teeth-management-system-b60a7',
    storageBucket: 'teeth-management-system-b60a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterMoblieApp',
  );
}


