targets:
  $default:
    builders:
      vector_graphics_compiler:vector_graphics:
        options:
          # Preserve the original colors from the SVG
          themeable: false
          # Keep the original paths and shapes
          pretty: true
          # Don't remove any IDs from the SVG
          keep_ids: true
          # Don't remove any unused definitions
          keep_defs: true
